### ISSUE TITLE
!includesub does not work

### ISSUE THREAD

**Issue by lyndsysimon** [quantorconsulting/mkdocs_build_plantuml#16]
I'm trying to build a series of diagrams which are composed of subparts, all of which are defined in a single `all.uml` file.

When I run `mkdocs build`, I get the following error:

```
Could not open [Errno 2] No such file or directory: '/Users/lyndsysimon/notes/notes/diagrams/src/ub all.uml!MY_SUB'
```

ETA: If the above isn't clear, I can provide a minimal example reproducing the issue.

**Comment by christo-ph** [comment]
Hi, sorry for the late response.

Currently I do not have the time to investigate further, but afair `!includesub` is not supported yet.

I am always open for PR.

**Comment by aarons20** [comment]
I experienced the same issue here. Is there already a fix available?
